[build]
# rustflags = ["-Zpolonius"]
# rustflags = ["-Zpolonius", "-C", "link-arg=-fuse-ld=mold"]
rustflags = ["-Zthreads=20"]
target-dir = ".target"

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"
